version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - ">= 4.5.a, < 4.6"
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - ">= 4.6.a, < 4.7"
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - ">= 4.7.a, < 4.8"
  - dependency-name: io.fabric8:docker-maven-plugin
    versions:
    - ">= 7.a, < 8"
  - dependency-name: org.apache.camel:camel-blueprint
    versions:
    - ">= 2.24.a, < 2.25"
  - dependency-name: org.apache.camel:camel-blueprint
    versions:
    - ">= 2.25.a, < 2.26"
  - dependency-name: org.apache.camel:camel-blueprint
    versions:
    - ">= 3.a, < 3.999999"
  - dependency-name: org.apache.camel:camel-blueprint
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.apache.camel:camel-core
    versions:
    - ">= 2.24.a, < 2.25"
  - dependency-name: org.apache.camel:camel-core
    versions:
    - ">= 2.25.a, < 2.26"
  - dependency-name: org.apache.camel:camel-core
    versions:
    - ">= 3.a, < 3.999999"
  - dependency-name: org.apache.camel:camel-core
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.apache.camel:camel-core-xml
    versions:
    - ">= 2.24.a, < 2.25"
  - dependency-name: org.apache.camel:camel-core-xml
    versions:
    - ">= 2.25.a, < 2.26"
  - dependency-name: org.apache.camel:camel-core-xml
    versions:
    - ">= 3.a, < 3.999999"
  - dependency-name: org.apache.camel:camel-core-xml
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.apache.camel:camel-maven-plugin
    versions:
    - ">= 2.24.a, < 2.25"
  - dependency-name: org.apache.camel:camel-maven-plugin
    versions:
    - ">= 2.25.a, < 2.26"
  - dependency-name: org.apache.camel:camel-parent
    versions:
    - ">= 2.24.a, < 2.25"
  - dependency-name: org.apache.camel:camel-parent
    versions:
    - ">= 2.25.a, < 2.26"
  - dependency-name: org.apache.camel:camel-parent
    versions:
    - ">= 3.a, < 3.999999"
  - dependency-name: org.apache.camel:camel-parent
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.apache.camel:camel-spring-javaconfig
    versions:
    - ">= 2.24.a, < 2.25"
  - dependency-name: org.apache.camel:camel-spring-javaconfig
    versions:
    - ">= 2.25.a, < 2.26"
  - dependency-name: org.apache.camel:camel-spring-javaconfig
    versions:
    - ">= 3.a, < 3.999999"
  - dependency-name: org.apache.camel:camel-spring-javaconfig
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.apache.camel:camel-test-karaf
    versions:
    - ">= 2.24.a, < 2.25"
  - dependency-name: org.apache.camel:camel-test-karaf
    versions:
    - ">= 2.25.a, < 2.26"
  - dependency-name: org.apache.camel:camel-test-karaf
    versions:
    - ">= 3.a, < 3.999999"
  - dependency-name: org.apache.camel:camel-test-karaf
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.apache.camel:camel-test-spring
    versions:
    - ">= 2.24.a, < 2.25"
  - dependency-name: org.apache.camel:camel-test-spring
    versions:
    - ">= 2.25.a, < 2.26"
  - dependency-name: org.apache.camel:camel-test-spring
    versions:
    - ">= 3.a, < 3.999999"
  - dependency-name: org.apache.camel:camel-test-spring
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.apache.camel:camel-twitter
    versions:
    - ">= 2.24.a, < 2.25"
  - dependency-name: org.apache.camel:camel-twitter
    versions:
    - ">= 2.25.a, < 2.26"
  - dependency-name: org.apache.camel:camel-twitter
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.apache.maven.plugins:maven-javadoc-plugin
    versions:
    - ">= 3.2.a, < 3.3"
  - dependency-name: org.jboss.resteasy:resteasy-spring-boot-starter
    versions:
    - ">= 2.a, < 3"
  - dependency-name: org.jboss.resteasy:resteasy-spring-boot-starter
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - ">= 2.2.a, < 2.3"
  - dependency-name: org.springframework.boot:spring-boot-maven-plugin
    versions:
    - ">= 2.2.a, < 2.3"
  - dependency-name: org.springframework:spring-test
    versions:
    - "> 5.1.14.RELEASE, < 5.2"
  - dependency-name: org.springframework:spring-test
    versions:
    - ">= 5.2.a, < 5.3"
