[[internal-design-time-service]]
== Design Time Service

Design Time Service is a set of REST API which provide background services to be used by the Data Mapper UI behind the scene. There are 4 types of Design Time Service:

=== Core Service
* Code Location: https://github.com/atlasmap/atlasmap/blob/master/lib/service
* API Reference: link:openapi/core/index.html[API]

Core Service provides basic operations which is not specific to the individual data formats, Create/Get/Update/Remove mapping definition stored in Design Time Service local storage, validate mapping, retrieve metadata for available field actions and etc. 

=== Java Service
* Code Location: https://github.com/atlasmap/atlasmap/blob/master/lib/modules/java/service
* API Reference: link:openapi/java/index.html[API]

Java Service provides Java inspection service which generate an AtlasMap Document object from Java class name.

=== JSON Service
* Code Location: https://github.com/atlasmap/atlasmap/blob/master/lib/modules/json/service
* API Reference: link:openapi/json/index.html[API]

JSON Service provides JSON inspection service which generate an AtlasMap Document object from JSON instance or JSON schema.

=== XML Service
* Code Location: https://github.com/atlasmap/atlasmap/blob/master/lib/modules/xml/service
* API Reference: link:openapi/xml/index.html[API]

XML Service provides XML inspection service which generate an AtlasMap Document object from XML instance or XML schema.

=== DFDL Service
* Code Location: https://github.com/atlasmap/atlasmap/blob/master/lib/modules/dfdl/service
* API Reference: link:openapi/dfdl/index.html[API]

XML Service provides XML inspection service which generate an AtlasMap Document object from XML instance or XML schema.
