/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 02 02:58:34 EST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject CollaborationGroupMember
 */
@XStreamAlias("CollaborationGroupMember")
public class CollaborationGroupMember extends AbstractSObjectBase {

    // CollaborationGroupId
    private String CollaborationGroupId;

    @JsonProperty("CollaborationGroupId")
    public String getCollaborationGroupId() {
        return this.CollaborationGroupId;
    }

    @JsonProperty("CollaborationGroupId")
    public void setCollaborationGroupId(String CollaborationGroupId) {
        this.CollaborationGroupId = CollaborationGroupId;
    }

    // MemberId
    private String MemberId;

    @JsonProperty("MemberId")
    public String getMemberId() {
        return this.MemberId;
    }

    @JsonProperty("MemberId")
    public void setMemberId(String MemberId) {
        this.MemberId = MemberId;
    }

    // CollaborationRole
    @XStreamConverter(PicklistEnumConverter.class)
    private CollaborationRoleEnum CollaborationRole;

    @JsonProperty("CollaborationRole")
    public CollaborationRoleEnum getCollaborationRole() {
        return this.CollaborationRole;
    }

    @JsonProperty("CollaborationRole")
    public void setCollaborationRole(CollaborationRoleEnum CollaborationRole) {
        this.CollaborationRole = CollaborationRole;
    }

    // NotificationFrequency
    @XStreamConverter(PicklistEnumConverter.class)
    private NotificationFrequencyEnum NotificationFrequency;

    @JsonProperty("NotificationFrequency")
    public NotificationFrequencyEnum getNotificationFrequency() {
        return this.NotificationFrequency;
    }

    @JsonProperty("NotificationFrequency")
    public void setNotificationFrequency(NotificationFrequencyEnum NotificationFrequency) {
        this.NotificationFrequency = NotificationFrequency;
    }

}
