/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 02 02:58:34 EST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject EmailServicesAddress
 */
@XStreamAlias("EmailServicesAddress")
public class EmailServicesAddress extends AbstractSObjectBase {

    // IsActive
    private Boolean IsActive;

    @JsonProperty("IsActive")
    public Boolean getIsActive() {
        return this.IsActive;
    }

    @JsonProperty("IsActive")
    public void setIsActive(Boolean IsActive) {
        this.IsActive = IsActive;
    }

    // LocalPart
    private String LocalPart;

    @JsonProperty("LocalPart")
    public String getLocalPart() {
        return this.LocalPart;
    }

    @JsonProperty("LocalPart")
    public void setLocalPart(String LocalPart) {
        this.LocalPart = LocalPart;
    }

    // EmailDomainName
    private String EmailDomainName;

    @JsonProperty("EmailDomainName")
    public String getEmailDomainName() {
        return this.EmailDomainName;
    }

    @JsonProperty("EmailDomainName")
    public void setEmailDomainName(String EmailDomainName) {
        this.EmailDomainName = EmailDomainName;
    }

    // AuthorizedSenders
    private String AuthorizedSenders;

    @JsonProperty("AuthorizedSenders")
    public String getAuthorizedSenders() {
        return this.AuthorizedSenders;
    }

    @JsonProperty("AuthorizedSenders")
    public void setAuthorizedSenders(String AuthorizedSenders) {
        this.AuthorizedSenders = AuthorizedSenders;
    }

    // RunAsUserId
    private String RunAsUserId;

    @JsonProperty("RunAsUserId")
    public String getRunAsUserId() {
        return this.RunAsUserId;
    }

    @JsonProperty("RunAsUserId")
    public void setRunAsUserId(String RunAsUserId) {
        this.RunAsUserId = RunAsUserId;
    }

    // FunctionId
    private String FunctionId;

    @JsonProperty("FunctionId")
    public String getFunctionId() {
        return this.FunctionId;
    }

    @JsonProperty("FunctionId")
    public void setFunctionId(String FunctionId) {
        this.FunctionId = FunctionId;
    }

}
