/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 02 02:58:34 EST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject EventRelation
 */
@XStreamAlias("EventRelation")
public class EventRelation extends AbstractSObjectBase {

    // RelationId
    private String RelationId;

    @JsonProperty("RelationId")
    public String getRelationId() {
        return this.RelationId;
    }

    @JsonProperty("RelationId")
    public void setRelationId(String RelationId) {
        this.RelationId = RelationId;
    }

    // EventId
    private String EventId;

    @JsonProperty("EventId")
    public String getEventId() {
        return this.EventId;
    }

    @JsonProperty("EventId")
    public void setEventId(String EventId) {
        this.EventId = EventId;
    }

    // Status
    @XStreamConverter(PicklistEnumConverter.class)
    private StatusEnum Status;

    @JsonProperty("Status")
    public StatusEnum getStatus() {
        return this.Status;
    }

    @JsonProperty("Status")
    public void setStatus(StatusEnum Status) {
        this.Status = Status;
    }

    // RespondedDate
    private org.joda.time.DateTime RespondedDate;

    @JsonProperty("RespondedDate")
    public org.joda.time.DateTime getRespondedDate() {
        return this.RespondedDate;
    }

    @JsonProperty("RespondedDate")
    public void setRespondedDate(org.joda.time.DateTime RespondedDate) {
        this.RespondedDate = RespondedDate;
    }

    // Response
    private String Response;

    @JsonProperty("Response")
    public String getResponse() {
        return this.Response;
    }

    @JsonProperty("Response")
    public void setResponse(String Response) {
        this.Response = Response;
    }

}
