/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 02 02:58:34 EST 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist IntegrationStage__c
 */
public enum IntegrationStageEnum {

    // Lead
    LEAD("Lead"),
    // Briefing
    BRIEFING("Briefing"),
    // Proposal
    PROPOSAL("Proposal"),
    // Negotiation
    NEGOTIATION("Negotiation"),
    // Closed Win
    CLOSED_WIN("Closed Win"),
    // Closed Lost
    CLOSED_LOST("Closed Lost");

    final String value;

    private IntegrationStageEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static IntegrationStageEnum fromValue(String value) {
        for (IntegrationStageEnum e : IntegrationStageEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
