/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 02 02:58:34 EST 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Ownership
 */
public enum OwnershipEnum {

    // Public
    PUBLIC("Public"),
    // Private
    PRIVATE("Private"),
    // Subsidiary
    SUBSIDIARY("Subsidiary"),
    // Other
    OTHER("Other");

    final String value;

    private OwnershipEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static OwnershipEnum fromValue(String value) {
        for (OwnershipEnum e : OwnershipEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
