/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 02 02:58:34 EST 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist PortalType
 */
public enum PortalTypeEnum {

    // None
    NONE("None"),
    // CustomerPortal
    CUSTOMERPORTAL("CustomerPortal"),
    // Partner
    PARTNER("Partner");

    final String value;

    private PortalTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static PortalTypeEnum fromValue(String value) {
        for (PortalTypeEnum e : PortalTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
