/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 02 02:58:34 EST 2015
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist TemplateType
 */
public enum TemplateTypeEnum {

    // text
    TEXT("text"),
    // html
    HTML("html"),
    // custom
    CUSTOM("custom"),
    // visualforce
    VISUALFORCE("visualforce");

    final String value;

    private TemplateTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static TemplateTypeEnum fromValue(String value) {
        for (TemplateTypeEnum e : TemplateTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
