
[[_atlas-service-json-definitions]]
== Definitions

[[_atlas-service-json-actions]]
=== Actions
__Type__ : object


[[_atlas-service-json-field]]
=== Field

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**actions** +
__optional__|<<_atlas-service-json-actions,Actions>>
|**arrayDimensions** +
__optional__|integer (int32)
|**arraySize** +
__optional__|integer (int32)
|**collectionType** +
__optional__|enum (ALL, ARRAY, LIST, MAP, NONE)
|**docId** +
__optional__|string
|**fieldType** +
__optional__|enum (ANY, ANY_DATE, BIG_INTEGER, BOOLEAN, BYTE, BYTE_ARRAY, CHAR, COMPLEX, DATE, DATE_TIME, DATE_TIME_TZ, DATE_TZ, DECIMAL, DOUBLE, FLOAT, INTEGER, LONG, NONE, NUMBER, SHORT, STRING, TIME, TIME_TZ, UNSIGNED_BYTE, UNSIGNED_INTEGER, UNSIGNED_LONG, UNSIGNED_SHORT, UNSUPPORTED)
|**format** +
__optional__|string
|**index** +
__optional__|integer (int32)
|**path** +
__optional__|string
|**required** +
__optional__|boolean
|**status** +
__optional__|enum (SUPPORTED, UNSUPPORTED, CACHED, ERROR, NOT_FOUND, BLACK_LIST)
|**value** +
__optional__|object
|===


[[_atlas-service-json-fields]]
=== Fields

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**field** +
__optional__|< <<_atlas-service-json-field,Field>> > array
|===


[[_atlas-service-json-jsondocument]]
=== JsonDocument

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**fields** +
__required__|<<_atlas-service-json-fields,Fields>>
|===


[[_atlas-service-json-jsoninspectionresponse]]
=== JsonInspectionResponse

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**errorMessage** +
__optional__|string
|**executionTime** +
__optional__|integer (int64)
|**jsonDocument** +
__optional__|<<_atlas-service-json-jsondocument,JsonDocument>>
|===



