[id='about-transforming-a-field-in-atlasmap']
= About transforming a field in AtlasMap 

In a data mapping, you can apply a transformation to one or more fields. 
A transformation is a function that AtlasMap performs on the selected 
field. For example, suppose you select a source field and specify 
the `Uppercase` transformation. At runtime, AtlasMap converts the source 
field value to uppercase and inserts the uppercase value in the target field.

To apply a transformation, select a source or target terminal field, 
click *Add Transformation* in the *Mapping Details* panel on the right, 
and select the transformation.

You can apply different transformations to different fields in the same mapping. 

In a one-to-one mapping, which maps one source field to one target field, 
it does not matter whether you apply the transformation to the source field 
or the target field. In a one-to-many or many-to-one mapping, consider 
what the target field value needs to be when you specify a transformation. 
For example, consider a many-to-one mapping that combines source fields 
for number, street, city, and state into one target address field. 
If you want the strings in the target address field to all be uppercase, 
select the target address field and apply the uppercase transformation. 
If only the state needs to be uppercase, select the source state field, 
and apply the uppercase transformation. 

You can think of a source field transformation as performing pre-processing, 
while a target field transformation performs post-processing. 
