
[[quickstart]]
= Quickstart

== Running Data Mapper UI within Syndesis

The easiest way to install and run Data Mapper UI is to install and run https://syndesis.io[Syndesis]. Simply follow the https://doc.syndesis.io[Syndesis Developer Handbook] to install, and run Syndesis UI. You will find the Data Mapper UI under the integrations panel after selecting or adding an integration with a data mapping step involved in the integration.


== Running AtlasMap standalone

Here is the shortest path to run standalone AtlasMap.

1. Clone AtlasMap repository
+
```
$ git clone https://github.com/atlasmap/atlasmap ${ATLASMAP}
```
+
2. Build AtlasMap runtime
+
```
$ cd ${ATLASMAP}
$ sh build.sh --skip-tests
```
+
3. Run AtlasMap Design Service
+
```
$ cd ${ATLASMAP}/runtime/runtime
$ ../../mvnw -Pitests spring-boot:run
```
+
4. https://yarnpkg.com/lang/en/docs/install/[Install Yarn]
+
5. In another console, install Data Mapper UI's dependencies
+
```
$ cd ${ATLASMAP}/ui
$ yarn install
```
+
6. Start Data Mapper UI
+
```
$ yarn start
```
+
The **yarn start** command will attempt to automatically open your browser window, but if it doesn't, open it directy with this URL: <http://localhost:3000>.



== Running AtlasMap full build

- Building everything for standalone usage
+
```
$ ./build.sh --skip-image-builds
```
+
To see all the available options:
+
```
$ ./build.sh --help
```
+
- Resume from module
+
To resume from a particular module:
+
```
$ ./build.sh --skip-image-builds --resume-from ui
```
+
- Using the image streams (in case you want to build a docker image for design runtime)
+
To build everything using image streams (instead of directly talking to docker):
+
```
$ ./build.sh --with-image-streams
```
+
Note that this assumes that you are using a template flavor that also supports image streams.

include::_tips_for_ui_developer.adoc[]
