/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 02 02:58:34 EST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject CallCenter
 */
@XStreamAlias("CallCenter")
public class CallCenter extends AbstractSObjectBase {

    // InternalName
    private String InternalName;

    @JsonProperty("InternalName")
    public String getInternalName() {
        return this.InternalName;
    }

    @JsonProperty("InternalName")
    public void setInternalName(String InternalName) {
        this.InternalName = InternalName;
    }

    // Version
    private Double Version;

    @JsonProperty("Version")
    public Double getVersion() {
        return this.Version;
    }

    @JsonProperty("Version")
    public void setVersion(Double Version) {
        this.Version = Version;
    }

    // AdapterUrl
    private String AdapterUrl;

    @JsonProperty("AdapterUrl")
    public String getAdapterUrl() {
        return this.AdapterUrl;
    }

    @JsonProperty("AdapterUrl")
    public void setAdapterUrl(String AdapterUrl) {
        this.AdapterUrl = AdapterUrl;
    }

    // CustomSettings
    private String CustomSettings;

    @JsonProperty("CustomSettings")
    public String getCustomSettings() {
        return this.CustomSettings;
    }

    @JsonProperty("CustomSettings")
    public void setCustomSettings(String CustomSettings) {
        this.CustomSettings = CustomSettings;
    }

}
