/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 02 02:58:34 EST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject CaseShare
 */
@XStreamAlias("CaseShare")
public class CaseShare extends AbstractSObjectBase {

    // CaseId
    private String CaseId;

    @JsonProperty("CaseId")
    public String getCaseId() {
        return this.CaseId;
    }

    @JsonProperty("CaseId")
    public void setCaseId(String CaseId) {
        this.CaseId = CaseId;
    }

    // UserOrGroupId
    private String UserOrGroupId;

    @JsonProperty("UserOrGroupId")
    public String getUserOrGroupId() {
        return this.UserOrGroupId;
    }

    @JsonProperty("UserOrGroupId")
    public void setUserOrGroupId(String UserOrGroupId) {
        this.UserOrGroupId = UserOrGroupId;
    }

    // CaseAccessLevel
    @XStreamConverter(PicklistEnumConverter.class)
    private CaseAccessLevelEnum CaseAccessLevel;

    @JsonProperty("CaseAccessLevel")
    public CaseAccessLevelEnum getCaseAccessLevel() {
        return this.CaseAccessLevel;
    }

    @JsonProperty("CaseAccessLevel")
    public void setCaseAccessLevel(CaseAccessLevelEnum CaseAccessLevel) {
        this.CaseAccessLevel = CaseAccessLevel;
    }

    // RowCause
    @XStreamConverter(PicklistEnumConverter.class)
    private RowCauseEnum RowCause;

    @JsonProperty("RowCause")
    public RowCauseEnum getRowCause() {
        return this.RowCause;
    }

    @JsonProperty("RowCause")
    public void setRowCause(RowCauseEnum RowCause) {
        this.RowCause = RowCause;
    }

}
