/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 02 02:58:34 EST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject Contract
 */
@XStreamAlias("Contract")
public class Contract extends AbstractSObjectBase {

    // AccountId
    private String AccountId;

    @JsonProperty("AccountId")
    public String getAccountId() {
        return this.AccountId;
    }

    @JsonProperty("AccountId")
    public void setAccountId(String AccountId) {
        this.AccountId = AccountId;
    }

    // Pricebook2Id
    private String Pricebook2Id;

    @JsonProperty("Pricebook2Id")
    public String getPricebook2Id() {
        return this.Pricebook2Id;
    }

    @JsonProperty("Pricebook2Id")
    public void setPricebook2Id(String Pricebook2Id) {
        this.Pricebook2Id = Pricebook2Id;
    }

    // OwnerExpirationNotice
    @XStreamConverter(PicklistEnumConverter.class)
    private OwnerExpirationNoticeEnum OwnerExpirationNotice;

    @JsonProperty("OwnerExpirationNotice")
    public OwnerExpirationNoticeEnum getOwnerExpirationNotice() {
        return this.OwnerExpirationNotice;
    }

    @JsonProperty("OwnerExpirationNotice")
    public void setOwnerExpirationNotice(OwnerExpirationNoticeEnum OwnerExpirationNotice) {
        this.OwnerExpirationNotice = OwnerExpirationNotice;
    }

    // StartDate
    private org.joda.time.DateTime StartDate;

    @JsonProperty("StartDate")
    public org.joda.time.DateTime getStartDate() {
        return this.StartDate;
    }

    @JsonProperty("StartDate")
    public void setStartDate(org.joda.time.DateTime StartDate) {
        this.StartDate = StartDate;
    }

    // EndDate
    private org.joda.time.DateTime EndDate;

    @JsonProperty("EndDate")
    public org.joda.time.DateTime getEndDate() {
        return this.EndDate;
    }

    @JsonProperty("EndDate")
    public void setEndDate(org.joda.time.DateTime EndDate) {
        this.EndDate = EndDate;
    }

    // BillingStreet
    private String BillingStreet;

    @JsonProperty("BillingStreet")
    public String getBillingStreet() {
        return this.BillingStreet;
    }

    @JsonProperty("BillingStreet")
    public void setBillingStreet(String BillingStreet) {
        this.BillingStreet = BillingStreet;
    }

    // BillingCity
    private String BillingCity;

    @JsonProperty("BillingCity")
    public String getBillingCity() {
        return this.BillingCity;
    }

    @JsonProperty("BillingCity")
    public void setBillingCity(String BillingCity) {
        this.BillingCity = BillingCity;
    }

    // BillingState
    private String BillingState;

    @JsonProperty("BillingState")
    public String getBillingState() {
        return this.BillingState;
    }

    @JsonProperty("BillingState")
    public void setBillingState(String BillingState) {
        this.BillingState = BillingState;
    }

    // BillingPostalCode
    private String BillingPostalCode;

    @JsonProperty("BillingPostalCode")
    public String getBillingPostalCode() {
        return this.BillingPostalCode;
    }

    @JsonProperty("BillingPostalCode")
    public void setBillingPostalCode(String BillingPostalCode) {
        this.BillingPostalCode = BillingPostalCode;
    }

    // BillingCountry
    private String BillingCountry;

    @JsonProperty("BillingCountry")
    public String getBillingCountry() {
        return this.BillingCountry;
    }

    @JsonProperty("BillingCountry")
    public void setBillingCountry(String BillingCountry) {
        this.BillingCountry = BillingCountry;
    }

    // ContractTerm
    private Integer ContractTerm;

    @JsonProperty("ContractTerm")
    public Integer getContractTerm() {
        return this.ContractTerm;
    }

    @JsonProperty("ContractTerm")
    public void setContractTerm(Integer ContractTerm) {
        this.ContractTerm = ContractTerm;
    }

    // Status
    @XStreamConverter(PicklistEnumConverter.class)
    private StatusEnum Status;

    @JsonProperty("Status")
    public StatusEnum getStatus() {
        return this.Status;
    }

    @JsonProperty("Status")
    public void setStatus(StatusEnum Status) {
        this.Status = Status;
    }

    // CompanySignedId
    private String CompanySignedId;

    @JsonProperty("CompanySignedId")
    public String getCompanySignedId() {
        return this.CompanySignedId;
    }

    @JsonProperty("CompanySignedId")
    public void setCompanySignedId(String CompanySignedId) {
        this.CompanySignedId = CompanySignedId;
    }

    // CompanySignedDate
    private org.joda.time.DateTime CompanySignedDate;

    @JsonProperty("CompanySignedDate")
    public org.joda.time.DateTime getCompanySignedDate() {
        return this.CompanySignedDate;
    }

    @JsonProperty("CompanySignedDate")
    public void setCompanySignedDate(org.joda.time.DateTime CompanySignedDate) {
        this.CompanySignedDate = CompanySignedDate;
    }

    // CustomerSignedId
    private String CustomerSignedId;

    @JsonProperty("CustomerSignedId")
    public String getCustomerSignedId() {
        return this.CustomerSignedId;
    }

    @JsonProperty("CustomerSignedId")
    public void setCustomerSignedId(String CustomerSignedId) {
        this.CustomerSignedId = CustomerSignedId;
    }

    // CustomerSignedTitle
    private String CustomerSignedTitle;

    @JsonProperty("CustomerSignedTitle")
    public String getCustomerSignedTitle() {
        return this.CustomerSignedTitle;
    }

    @JsonProperty("CustomerSignedTitle")
    public void setCustomerSignedTitle(String CustomerSignedTitle) {
        this.CustomerSignedTitle = CustomerSignedTitle;
    }

    // CustomerSignedDate
    private org.joda.time.DateTime CustomerSignedDate;

    @JsonProperty("CustomerSignedDate")
    public org.joda.time.DateTime getCustomerSignedDate() {
        return this.CustomerSignedDate;
    }

    @JsonProperty("CustomerSignedDate")
    public void setCustomerSignedDate(org.joda.time.DateTime CustomerSignedDate) {
        this.CustomerSignedDate = CustomerSignedDate;
    }

    // SpecialTerms
    private String SpecialTerms;

    @JsonProperty("SpecialTerms")
    public String getSpecialTerms() {
        return this.SpecialTerms;
    }

    @JsonProperty("SpecialTerms")
    public void setSpecialTerms(String SpecialTerms) {
        this.SpecialTerms = SpecialTerms;
    }

    // ActivatedById
    private String ActivatedById;

    @JsonProperty("ActivatedById")
    public String getActivatedById() {
        return this.ActivatedById;
    }

    @JsonProperty("ActivatedById")
    public void setActivatedById(String ActivatedById) {
        this.ActivatedById = ActivatedById;
    }

    // ActivatedDate
    private org.joda.time.DateTime ActivatedDate;

    @JsonProperty("ActivatedDate")
    public org.joda.time.DateTime getActivatedDate() {
        return this.ActivatedDate;
    }

    @JsonProperty("ActivatedDate")
    public void setActivatedDate(org.joda.time.DateTime ActivatedDate) {
        this.ActivatedDate = ActivatedDate;
    }

    // StatusCode
    @XStreamConverter(PicklistEnumConverter.class)
    private StatusCodeEnum StatusCode;

    @JsonProperty("StatusCode")
    public StatusCodeEnum getStatusCode() {
        return this.StatusCode;
    }

    @JsonProperty("StatusCode")
    public void setStatusCode(StatusCodeEnum StatusCode) {
        this.StatusCode = StatusCode;
    }

    // Description
    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

    // ContractNumber
    private String ContractNumber;

    @JsonProperty("ContractNumber")
    public String getContractNumber() {
        return this.ContractNumber;
    }

    @JsonProperty("ContractNumber")
    public void setContractNumber(String ContractNumber) {
        this.ContractNumber = ContractNumber;
    }

    // LastApprovedDate
    private org.joda.time.DateTime LastApprovedDate;

    @JsonProperty("LastApprovedDate")
    public org.joda.time.DateTime getLastApprovedDate() {
        return this.LastApprovedDate;
    }

    @JsonProperty("LastApprovedDate")
    public void setLastApprovedDate(org.joda.time.DateTime LastApprovedDate) {
        this.LastApprovedDate = LastApprovedDate;
    }

}
