/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 02 02:58:34 EST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject EmailTemplate
 */
@XStreamAlias("EmailTemplate")
public class EmailTemplate extends AbstractSObjectBase {

    // DeveloperName
    private String DeveloperName;

    @JsonProperty("DeveloperName")
    public String getDeveloperName() {
        return this.DeveloperName;
    }

    @JsonProperty("DeveloperName")
    public void setDeveloperName(String DeveloperName) {
        this.DeveloperName = DeveloperName;
    }

    // NamespacePrefix
    private String NamespacePrefix;

    @JsonProperty("NamespacePrefix")
    public String getNamespacePrefix() {
        return this.NamespacePrefix;
    }

    @JsonProperty("NamespacePrefix")
    public void setNamespacePrefix(String NamespacePrefix) {
        this.NamespacePrefix = NamespacePrefix;
    }

    // FolderId
    private String FolderId;

    @JsonProperty("FolderId")
    public String getFolderId() {
        return this.FolderId;
    }

    @JsonProperty("FolderId")
    public void setFolderId(String FolderId) {
        this.FolderId = FolderId;
    }

    // BrandTemplateId
    private String BrandTemplateId;

    @JsonProperty("BrandTemplateId")
    public String getBrandTemplateId() {
        return this.BrandTemplateId;
    }

    @JsonProperty("BrandTemplateId")
    public void setBrandTemplateId(String BrandTemplateId) {
        this.BrandTemplateId = BrandTemplateId;
    }

    // TemplateStyle
    @XStreamConverter(PicklistEnumConverter.class)
    private TemplateStyleEnum TemplateStyle;

    @JsonProperty("TemplateStyle")
    public TemplateStyleEnum getTemplateStyle() {
        return this.TemplateStyle;
    }

    @JsonProperty("TemplateStyle")
    public void setTemplateStyle(TemplateStyleEnum TemplateStyle) {
        this.TemplateStyle = TemplateStyle;
    }

    // IsActive
    private Boolean IsActive;

    @JsonProperty("IsActive")
    public Boolean getIsActive() {
        return this.IsActive;
    }

    @JsonProperty("IsActive")
    public void setIsActive(Boolean IsActive) {
        this.IsActive = IsActive;
    }

    // TemplateType
    @XStreamConverter(PicklistEnumConverter.class)
    private TemplateTypeEnum TemplateType;

    @JsonProperty("TemplateType")
    public TemplateTypeEnum getTemplateType() {
        return this.TemplateType;
    }

    @JsonProperty("TemplateType")
    public void setTemplateType(TemplateTypeEnum TemplateType) {
        this.TemplateType = TemplateType;
    }

    // Encoding
    @XStreamConverter(PicklistEnumConverter.class)
    private EncodingEnum Encoding;

    @JsonProperty("Encoding")
    public EncodingEnum getEncoding() {
        return this.Encoding;
    }

    @JsonProperty("Encoding")
    public void setEncoding(EncodingEnum Encoding) {
        this.Encoding = Encoding;
    }

    // Description
    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

    // Subject
    private String Subject;

    @JsonProperty("Subject")
    public String getSubject() {
        return this.Subject;
    }

    @JsonProperty("Subject")
    public void setSubject(String Subject) {
        this.Subject = Subject;
    }

    // HtmlValue
    private String HtmlValue;

    @JsonProperty("HtmlValue")
    public String getHtmlValue() {
        return this.HtmlValue;
    }

    @JsonProperty("HtmlValue")
    public void setHtmlValue(String HtmlValue) {
        this.HtmlValue = HtmlValue;
    }

    // Body
    private String Body;

    @JsonProperty("Body")
    public String getBody() {
        return this.Body;
    }

    @JsonProperty("Body")
    public void setBody(String Body) {
        this.Body = Body;
    }

    // TimesUsed
    private Integer TimesUsed;

    @JsonProperty("TimesUsed")
    public Integer getTimesUsed() {
        return this.TimesUsed;
    }

    @JsonProperty("TimesUsed")
    public void setTimesUsed(Integer TimesUsed) {
        this.TimesUsed = TimesUsed;
    }

    // LastUsedDate
    private org.joda.time.DateTime LastUsedDate;

    @JsonProperty("LastUsedDate")
    public org.joda.time.DateTime getLastUsedDate() {
        return this.LastUsedDate;
    }

    @JsonProperty("LastUsedDate")
    public void setLastUsedDate(org.joda.time.DateTime LastUsedDate) {
        this.LastUsedDate = LastUsedDate;
    }

    // ApiVersion
    private Double ApiVersion;

    @JsonProperty("ApiVersion")
    public Double getApiVersion() {
        return this.ApiVersion;
    }

    @JsonProperty("ApiVersion")
    public void setApiVersion(Double ApiVersion) {
        this.ApiVersion = ApiVersion;
    }

    // Markup
    private String Markup;

    @JsonProperty("Markup")
    public String getMarkup() {
        return this.Markup;
    }

    @JsonProperty("Markup")
    public void setMarkup(String Markup) {
        this.Markup = Markup;
    }

}
