/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 02 02:58:34 EST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject OrderItem
 */
@XStreamAlias("OrderItem")
public class OrderItem extends AbstractSObjectBase {

    // OrderId
    private String OrderId;

    @JsonProperty("OrderId")
    public String getOrderId() {
        return this.OrderId;
    }

    @JsonProperty("OrderId")
    public void setOrderId(String OrderId) {
        this.OrderId = OrderId;
    }

    // PricebookEntryId
    private String PricebookEntryId;

    @JsonProperty("PricebookEntryId")
    public String getPricebookEntryId() {
        return this.PricebookEntryId;
    }

    @JsonProperty("PricebookEntryId")
    public void setPricebookEntryId(String PricebookEntryId) {
        this.PricebookEntryId = PricebookEntryId;
    }

    // OriginalOrderItemId
    private String OriginalOrderItemId;

    @JsonProperty("OriginalOrderItemId")
    public String getOriginalOrderItemId() {
        return this.OriginalOrderItemId;
    }

    @JsonProperty("OriginalOrderItemId")
    public void setOriginalOrderItemId(String OriginalOrderItemId) {
        this.OriginalOrderItemId = OriginalOrderItemId;
    }

    // Quantity
    private Double Quantity;

    @JsonProperty("Quantity")
    public Double getQuantity() {
        return this.Quantity;
    }

    @JsonProperty("Quantity")
    public void setQuantity(Double Quantity) {
        this.Quantity = Quantity;
    }

    // UnitPrice
    private Double UnitPrice;

    @JsonProperty("UnitPrice")
    public Double getUnitPrice() {
        return this.UnitPrice;
    }

    @JsonProperty("UnitPrice")
    public void setUnitPrice(Double UnitPrice) {
        this.UnitPrice = UnitPrice;
    }

    // ListPrice
    private Double ListPrice;

    @JsonProperty("ListPrice")
    public Double getListPrice() {
        return this.ListPrice;
    }

    @JsonProperty("ListPrice")
    public void setListPrice(Double ListPrice) {
        this.ListPrice = ListPrice;
    }

    // ServiceDate
    private org.joda.time.DateTime ServiceDate;

    @JsonProperty("ServiceDate")
    public org.joda.time.DateTime getServiceDate() {
        return this.ServiceDate;
    }

    @JsonProperty("ServiceDate")
    public void setServiceDate(org.joda.time.DateTime ServiceDate) {
        this.ServiceDate = ServiceDate;
    }

    // EndDate
    private org.joda.time.DateTime EndDate;

    @JsonProperty("EndDate")
    public org.joda.time.DateTime getEndDate() {
        return this.EndDate;
    }

    @JsonProperty("EndDate")
    public void setEndDate(org.joda.time.DateTime EndDate) {
        this.EndDate = EndDate;
    }

    // Description
    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

    // OrderItemNumber
    private String OrderItemNumber;

    @JsonProperty("OrderItemNumber")
    public String getOrderItemNumber() {
        return this.OrderItemNumber;
    }

    @JsonProperty("OrderItemNumber")
    public void setOrderItemNumber(String OrderItemNumber) {
        this.OrderItemNumber = OrderItemNumber;
    }

}
