
[[_atlas-service-xml-definitions]]
== Definitions

[[_atlas-service-xml-actions]]
=== Actions
__Type__ : object


[[_atlas-service-xml-field]]
=== Field

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**actions** +
__optional__|<<_atlas-service-xml-actions,Actions>>
|**arrayDimensions** +
__optional__|integer (int32)
|**arraySize** +
__optional__|integer (int32)
|**collectionType** +
__optional__|enum (ALL, ARRAY, LIST, MAP, NONE)
|**docId** +
__optional__|string
|**fieldType** +
__optional__|enum (ANY, ANY_DATE, BIG_INTEGER, BOOLEAN, BYTE, BYTE_ARRAY, CHAR, COMPLEX, DATE, DATE_TIME, DATE_TIME_TZ, DATE_TZ, DECIMAL, DOUBLE, FLOAT, INTEGER, LONG, NONE, NUMBER, SHORT, STRING, TIME, TIME_TZ, UNSIGNED_BYTE, UNSIGNED_INTEGER, UNSIGNED_LONG, UNSIGNED_SHORT, UNSUPPORTED)
|**format** +
__optional__|string
|**index** +
__optional__|integer (int32)
|**path** +
__optional__|string
|**required** +
__optional__|boolean
|**status** +
__optional__|enum (SUPPORTED, UNSUPPORTED, CACHED, ERROR, NOT_FOUND, BLACK_LIST)
|**value** +
__optional__|object
|===


[[_atlas-service-xml-fields]]
=== Fields

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**field** +
__optional__|< <<_atlas-service-xml-field,Field>> > array
|===


[[_atlas-service-xml-xmldocument]]
=== XmlDocument

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**fields** +
__optional__|<<_atlas-service-xml-fields,Fields>>
|**xmlNamespaces** +
__optional__|<<_atlas-service-xml-xmlnamespaces,XmlNamespaces>>
|===


[[_atlas-service-xml-xmlinspectionresponse]]
=== XmlInspectionResponse

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**errorMessage** +
__optional__|string
|**executionTime** +
__optional__|integer (int64)
|**xmlDocument** +
__optional__|<<_atlas-service-xml-xmldocument,XmlDocument>>
|===


[[_atlas-service-xml-xmlnamespace]]
=== XmlNamespace

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**alias** +
__optional__|string
|**locationUri** +
__optional__|string
|**targetNamespace** +
__optional__|boolean
|**uri** +
__optional__|string
|===


[[_atlas-service-xml-xmlnamespaces]]
=== XmlNamespaces

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**xmlNamespace** +
__optional__|< <<_atlas-service-xml-xmlnamespace,XmlNamespace>> > array
|===



