# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: __Experimental

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_maven:
    if: ${{ github.repository == 'atlasmap/atlasmap' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        java: [ '13', '15' ]
    name: Java ${{ matrix.Java }} build
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java versions
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Cache Maven repo
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: |
          ui/node_modules
          ui/packages/*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('ui/yarn.lock') }}
    - name: Build from root with Maven
      continue-on-error: true
      run: mvn --batch-mode -Pcoverage -Dwebdriver.chrome.driver=/usr/bin/chromedriver clean install
    - name: Build lib with Maven
      continue-on-error: true
      working-directory: lib
      run: mvn --batch-mode clean install
    - name: Build docs
      continue-on-error: true
      working-directory: docs
      run: mvn -Phtml,pdf package
    - name: Build aggregated javadoc
      continue-on-error: true
      working-directory: docs
      run: mvn -f pom-javadoc.xml  -Dfailonerror=true -pl \!io.atlasmap:atlasmap-lib-all javadoc:aggregate
  build_yarn:
    if: ${{ github.repository == 'atlasmap/atlasmap' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ '16' ]
    name: node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup node versions
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: yarn install
      continue-on-error: true
      working-directory: ui
      run: yarn install
    - name: --FIXME lerna build
      continue-on-error: true
      working-directory: ui
      run: yarn build
    - name: --FIXME yarn build @atlasmap/core
      continue-on-error: true
      working-directory: ui/packages/atlasmap-core
      run: yarn build
    - name: yarn build @atlasmap/atlasmap
      continue-on-error: true
      working-directory: ui/packages/atlasmap
      run: yarn build
    - name: yarn build:storybook @atlasmap/atlasmap
      continue-on-error: true
      working-directory: ui/packages/atlasmap
      run: yarn build:storybook
    - name: yarn build @atlasmap/atlasmap-standalone
      continue-on-error: true
      working-directory: ui/packages/atlasmap-standalone
      run: yarn build
      