# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: __Experimental

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_maven:
    if: ${{ github.repository == 'atlasmap/atlasmap' }}
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '18', '11' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: ${{ matrix.os }}/Java${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java versions
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Cache Maven repo
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build from root with Maven
      if: ${{ runner.os == 'Windows' }}
      run: mvn --batch-mode -Pcoverage "-Dwebdriver.chrome.driver=$Env:CHROMEWEBDRIVER\chromedriver.exe" clean install
    - name: Build from root with Maven
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: mvn --batch-mode -Pcoverage "-Dwebdriver.chrome.driver=${CHROMEWEBDRIVER}/chromedriver" clean install
    - name: Build lib with Maven
      working-directory: lib
      run: mvn --batch-mode clean install
    - name: Build docs
      working-directory: docs
      run: mvn -Phtml,pdf package
    - name: Build aggregated javadoc
      working-directory: docs
      run: mvn -f pom-javadoc.xml  -Dfailonerror=true -pl \!io.atlasmap:atlasmap-lib-all -pl \!io.atlasmap.com.sun.xsom:xsom javadoc:aggregate
