name: 'Main'

on:
  push:
    branches: [ main ]

jobs:
  build-main:
    if: ${{ github.repository == 'atlasmap/atlasmap' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Java versions
        uses: actions/setup-java@v2
        with:
          java-version: 18
          distribution: 'temurin'
      - name: Cache Maven repo
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: mvn --batch-mode -Pcoverage -Dwebdriver.chrome.driver=/usr/bin/chromedriver clean install
      - name: Publish docs
        run: sh publish-docs.sh
        working-directory: docs
      - name: Publish Docker Image
        run: |
          mvn --batch-mode -Pdocker \
            -Dimage.tag.primary=latest \
            -Djkube.docker.username=${{ secrets.DOCKER_USERNAME }} \
            -Djkube.docker.password=${{ secrets.DOCKER_PASSWORD }} \
            k8s:build k8s:push
        working-directory: standalone
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage-report/target/site/jacoco-aggregate/jacoco.xml,ui/packages/atlasmap-core/coverage/lcov.info,ui/packages/atlasmap/coverage/lcov.info,ui/packages/atlasmap-standalone/coverage/lcov.info
